### ISSUE TITLE
URL does not appear to be a Lemmy community URL.

### ISSUE THREAD

**Issue by kratoz29** [bunburya/lemmy2opml#1]
Hi, I'm getting the following issue:

`Could not fetch subscribed communities for user kratoz29 on site https://lemmy.world: URL does not appear to be a Lemmy community URL: https://kbin.social/m/kbinMeta
CRITICAL:root:Encountered an error (logs may provide further information): URL does not appear to be a Lemmy community URL: https://kbin.social/m/kbinMeta`

The command I'm using is the following:

`python3 ./lemmy2opml.py --password "password" export lemmy.world kratoz29 test.opml`

Am I doing something wrong? I'm on macOS.

Same bug with the lemmy.fmhy.ml instance.

**Comment by bunburya** [comment]
Thanks for flagging! You're not doing anything wrong, it just doesn't support exporting/importing Kbin magazines at the moment (as the URLs looks slightly different). It shouldn't take too long to add support so I will try do it shortly. In the meantime I have pushed a change that will make it skip exporting a community when it encounters a community-specific error (rather than just failing completely), so it should at least export your communities on Lemmy (but not Kbin) instances.
